### PR TITLE
latest crypt key updates from the dev wiki

### PR DESCRIPTION
**Pull request by WainPetopia**

### CODE REVIEW

**Comment by herrvigg** [comment]
hi,
just wondering about these keys.
What games do they concern, beside WoW and OW? For instance, is Heroes of the Storm also concerned?
Here they were provided by this wiki but generally speaking where do they come from?

**Comment by ladislav-zezula** [comment]
Look directly in the CascDecrypt.cpp. People who contributed the keys were very specific about for which game the particular key is. And the keys are added as soon as someone discovers them - i.e. when Blizzard makes them public.

**Comment by herrvigg** [comment]
Thanks for answering :)
Sure i see it's mostly WoW and OW but i don't really see what it concerns. Specific patches? Items? Models? Is a key fixed for ever for this stuff or can they change over time?
As i'm only using CascLib for heroes i was wondering if there might be some stuff that could be decoded 
later (is it related to the unknown items?). Also, what is the risk that everything gets encrypted?
Sorry many questions but i don't really have any clue about this part and it's interesting to know.

**Comment by ladislav-zezula** [comment]
> Sure i see it's mostly WoW and OW but i don't really see what it concerns. Specific patches? Items? Models?
Whatever that Blizzard wants to put into the data files but want to keep secret until a specific release.
> As i'm only using CascLib for heroes i was wondering if there might be some stuff that could be decoded
later (is it related to the unknown items?). Also, what is the risk that everything gets encrypted?
You have the key -> you can decrypt. You don't kave the key -> you cannot decrypt. As simple as that.

**Comment by herrvigg** [comment]
About the decoding i can reformulate it: when exploring the Casc for heroes there are a bunch of files still in the original binary format. Does this mean they are not decrypted because of a missing key or is it for another technical reason?

About the risk of being encrypted, have you already seen a case when things that were previously in clear or with a known key became encrypted with a new key?

**Comment by WainPetopia** [comment]
Sorry for the slow reply. 

I just grab the encryption key updates from the wiki page as it's updated:
https://wowdev.wiki/CASC#Encryption_keys

They only update keys for WoW and Overwatch, and I don't know if that's because Heroes doesn't use them or if the dataminers simply aren't interested in that title. I don't mine the keys myself so I can't tell you how it's done, sorry.

You could try asking on the Discussion page for that page I linked. Hopefully someone will see it and reply.

**Pull request merged**
