### PR TITLE
Fix include guards and macro definitions

### PR DESCRIPTION
**Pull request by doctaweeks**
Symbols that begin with underscores and double underscores are reserved

### CODE REVIEW

**Comment by ladislav-zezula** [comment]
So, basically you removed double underscore from any symbol guard? Was it worth the work?

**Comment by doctaweeks** [comment]
Yes, it protects from future implementation collisions and makes compilation behavior more predictable.

**Comment by doctaweeks** [comment]
See https://cs.nyu.edu/courses/fall11/CSCI-GA.2110-003/documents/c++2003std.pdf section 17.4.3.1.2 (page 327, pdf page 355)

**Comment by ladislav-zezula** [comment]
Thank you for your effort, but I am gonna close this pull request without change.

**Pull request closed without merging**
