### PR TITLE
* Enhanced file caching and handling in CASC library

### PR DESCRIPTION
**Pull request by JayDT**
Enhanced file caching and handling in CASC library

- **Modified CascCommon.h**: 
  - Added `CascCacheWholeFile` strategy in `CSTRTG` enum.
  
- **Updated CascLib.h**: 
  - Defined `CASC_CACHE_WHOLE_FILE` flag.
  - Declared new functions: `CascSetCacheStrategy` and `CascGetFileId`.
  
- **Implemented in CascOpenFile.cpp**:
  - Added `CascSetCacheStrategy` function to set cache strategy.
  - Added `CascGetFileId` function to retrieve file ID by name.
  
- **Enhanced ReadFile performance in CascReadFile.cpp**:
  - Implemented `ReadFile_WholeCached` function for whole file caching.
  - Optimized decoded buffer handling.
  - Fixed rare invalid read issue.
  
- **Improved CKeyEntry handling in FileTree.cpp and FileTree.h**:
  - Supported multiple keys in file nodes.
  - Enhanced insertion and retrieval methods for file nodes.
  
- **Improved file retrieval in RootHandler.cpp**:
  - Enhanced methods for getting files by name and ID.
  - Added new `GetInfo` method to retrieve file info by name.
  
- **Adjusted related struct and enum definitions**:
  - Updated `CASC_FILE_NODE` struct to support multiple keys.
  - Enhanced various methods to accommodate new caching strategy and file handling improvements.

### CODE REVIEW

**Comment by ladislav-zezula** [comment]
Hi, thanks for the contribution. This looks like quite a complex change, what is the use case?

**Comment by JayDT** [comment]
> Hi, thanks for the contribution. This looks like quite a complex change, what is the use case?

Hi,

Thanks for you message and for considering my contribution. The use case for these changes is as follows:

The CascCacheWholeFile method improved read performance when non-sequential file reading was needed, such as with M2 models.

In FileNodes, the same FileDataId had multiple CKeys, but only one of them was locally accessible. This often got overwritten by an online update, causing read failures.

During ReadFile, I reuse the pbEncoded buffer to reduce memory operations during reading.

CascGetFileId was useful when generating filenames for models and images, as it was simpler to store an integer for future use.

I tried to summarize this concisely.

**Comment by ladislav-zezula** [comment]
Okey.

> In FileNodes, the same FileDataId had multiple CKeys, but only one of them was locally accessible. This often got overwritten by an online update, causing read failures.

Would there be a chance that you shared such CASC storage? I would like to add it to my regression tests.

**Comment by JayDT** [comment]
> Okey.
> 
> > In FileNodes, the same FileDataId had multiple CKeys, but only one of them was locally accessible. This often got overwritten by an online update, causing read failures.
> 
> Would there be a chance that you shared such CASC storage? I would like to add it to my regression tests.

Unfortunately, my home upload speed is not sufficient to upload such a large amount of content in a reasonable time frame.

I encounter most issues with WoW Casc databases, most recently. I found that 8 ckeys are associated with 1 filedataid, and one of these was a local file. 
I also encountered this issue in older Cascs, especially those with a minimal client or where a patch change occurred.

**Comment by ladislav-zezula** [comment]
@JayDT I need you to fix the problems that I described in this PR before I merge this to master.

**Pull request merged**
