### PR TITLE
Support WoW 10.1.7

### PR DESCRIPTION
**Pull request by Shauren**

### CODE REVIEW

**Comment by ladislav-zezula** [comment]
Could you please make the pull request into https://github.com/ladislav-zezula/CascLib/tree/LZ_WoW_1017?
I would like to add the new build into regression tests before merging to master.

**Comment by Shauren** [comment]
Done, target branch changed

**Comment by ladislav-zezula** [comment]
Ok. let me work on this a bit. I'll then update both master CascLib and CascView.

**Comment by ladislav-zezula** [comment]
Done: https://github.com/ladislav-zezula/CascLib/pull/258

**Pull request merged**
